TERMINAL=ghostty
EDITOR=nvim
VISUAL=nvim
GOPATH=${HOME}/go
BUN_INSTALL=${HOME}/.bun
PATH=${HOME}/.local/bin:${HOME}/.local/share/mise/installs/go/1.26.3/bin:${HOME}/.local/share/mise/installs/node/lts/bin:${HOME}/go/bin:${HOME}/.cargo/bin:${HOME}/.bun/bin:${HOME}/.opencode/bin:$PATH
