set -g default-terminal "tmux-256color"
set -g escape-time 10
set -g focus-events on
set -g history-limit 50000
set -g mouse on
set -g renumber-windows on
set -g status-interval 5

set -g prefix C-a
unbind C-b
bind C-a send-prefix

setw -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel

bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

set -g status-left-length 40
set -g status-left "#[bold]#S #[default]"
set -g status-right "%Y-%m-%d %H:%M"
